name: mythu
favicon: null
layout_spectrum: 0.649977735010907
typography_spectrum: 0.03226120420731604
title: mythus design c.o.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6148601153399795
  lightness: 0.21613623737357557
  saturation: 0.4324824761133641
  rhythmicContrast: 0.7647185991518199
purpose: []
