name: mythu
favicon: null
layout_spectrum: 1
typography_spectrum: 0.56652
title: mythus design c.o.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f0d0c'
    - '#caa26d'
    - '#665132'
    - '#ffffca'
    - '#dedd9c'
  brandStrength: 0.8125
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
